spring:
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:./db/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8100
  servlet.context-path: /cathaybk-coindesk

coin-desk:
  api:
    url: https://api.coindesk.com/v1/bpi/currentprice.json